// <auto-generated />
namespace DynamicForms.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DynamicFormsContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DynamicFormsContext));
        
        string IMigrationMetadata.Id
        {
            get { return "202101091218586_DynamicFormsContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
